import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/section/layout/header";
import Scroll from "@/section/layout/scroll";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={poppins.className}>
        <Scroll />
        <div className="flex min-h-screen flex-col items-center p-6 xl:p-12 gap-6 xl:gap-12">
          <Header />

          <main className="flex w-full h-full flex-grow max-w-screen-xl mx-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
