import React from "react";
import { getDetail } from "../actions";
import ServerDetailPokemonView from "@/section/server/detail/view";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Loading Data... | Poke Render",
  description: "Generated by create next app",
};

interface ServerDetailPokemonProps {
  params: {
    name: string;
  };
}

export default async function ServerDetailPokemon({
  params,
}: ServerDetailPokemonProps) {
  const details = await getDetail(params?.name);

  return <ServerDetailPokemonView details={details} />;
}
