import { Metadata } from "next";
import React from "react";
import ServerView from "@/section/server/view";

export const metadata: Metadata = {
  title: "Server Side Rendering | Poke Render",
  description: "Generated by create next app",
};

export default async function ServerRendering() {
  return <ServerView />;
}
